version: '2'

services:
  flowchat_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: flowchat
  flowchat:
    build: .
    command: "bash -c 'sleep 7s; java -jar /opt/flowchat.jar -liquibase'"
    depends_on:
      - flowchat_db
    ports:
     - "4567:4567"
    environment:
      FLOWCHAT_DB_URL: "jdbc:postgresql://flowchat_db/flowchat"
      FLOWCHAT_DB_USERNAME: "postgres"
      FLOWCHAT_DB_PASSWORD: "example"
      SORTING_CREATED_WEIGHT: 86400
      SORTING_NUMBER_OF_VOTES_WEIGHT: 0.001
      SORTING_AVG_RANK_WEIGHT: 0.01